### ISSUE TITLE
How do I run doiuse purely in node? [documentation]

### ISSUE THREAD

**Issue by dominikwilkowski** [anandthakker/doiuse#11]
```js
doiuse({
	browsers:['ie >= 6', '> 1%'],
	onFeatureUsage: function(usageInfo) {
		console.log(usageInfo.message);
	}
});
```

That is missing the file reference... Any hints on that?

**Comment by anandthakker** [comment]
@dominikwilkowski There are a couple of ways:
1) streaming (take note of the first require--`doiuse/stream`)
```javascript
var fs = require('fs')
var doiuse = require('doiuse/stream');

fs.createReadStream('/path/to/your/file.css')
  .pipe(doiuse(['ie >= 8', '> 1%']))
  .on('data', function(usageInfo) {
     console.log(usageInfo.message)
   }
```

2) as a postcss plugin
```
var fs= require('fs')
var postcss = require('postcss')
var doiuse = require('doiuse')

postcss(doiuse({
    browsers:['ie >= 6', '> 1%'],
    onFeatureUsage: function(usageInfo) {
        console.log(usageInfo.message);
    }
}))
.process(fs.readFileSync('/path/to/your.css')
```

**Comment by dominikwilkowski** [comment]
great! Thanks.

**Comment by anandthakker** [comment]
No problem!

I'm gonna reopen this till I get a chance to add this to the readme.

**Comment by dominikwilkowski** [comment]
No worries...

In that case I might as well keep asking things ;)

```js
var fs = require('fs');
var doiuse = require('doiuse');

var sourceFile = 'test/fixtures/backgrounds.css';
var OPTIONS = [];
OPTIONS.browsers = [ '> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1' ];

fs
	.createReadStream( sourceFile )
	.pipe( doiuse( OPTIONS.browsers ) )
	.on('data', function( usageInfo ) {
		console.log(usageInfo.message)
	});
```

This returns:
```shell
$ node test.js
_stream_readable.js:495
  dest.on('unpipe', onunpipe);
       ^
TypeError: undefined is not a function
    at ReadStream.Readable.pipe (_stream_readable.js:495:8)
    at Object.<anonymous> (/Users/dominikwilkowski/Sites/grunt-doiuse/test.js:10:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

ps I am running Node `v0.12.0`...

Appreciate the help.

**Comment by anandthakker** [comment]
No problem.  I think the issue here is in your second line.  It should be:

var doiuse = require('doiuse/stream');

(`doiuse` is the postcss plugin, `doiuse/stream` is a more standalone
stream api)

**Comment by dominikwilkowski** [comment]
that did it! awesome
