### ISSUE TITLE
Gulp not working

### ISSUE THREAD

**Issue by ramrami** [anandthakker/doiuse#51]
I have this simple task : 
```javascript
var postcss = require('gulp-postcss');
var doiuse = require('doiuse');

//Not working :(
gulp.task('doiuse', function(){
  return gulp.src("./src/css/**/*.css")
      .pipe(postcss([
          doiuse({
              browsers: [
                  'ie >= 8',
                  '> 1%'
              ],
              onFeatureUsage: function (usageInfo) {
                  console.log(usageInfo.message);
              }
          })
      ]));
});
```
and get the following error : 
```
Error: Cannot find module 'postcss/lib/list'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Workspace\templates\corporate1\node_modules\doiuse\data\features.js:1:74)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```

`node v4.4.5`
`npm v2.15.5`
` gulp v3.9.1`
`gulp-postcss v6.1.1`

**Comment by ramrami** [comment]
My fault, re-run npm install and it's working now !
